title: Kasinobonuksia
description: Tervetuloa "kasinobonuksia ja kolikkopelejä" -sivustolle. Tämä on puhdas kasinoseikkailu! Tällä minisaitilla pääset lukemaan mielenkiintoisista
  kasinopeleistä ja bonuksista. Ja minä pääsen harjoittelemaan Githubin käyttöä. Win-win, eikö?
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com



paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Etusivu
   url: /index.html
 - title: Tietoa
   url: /about
 - title: Ota yhteyttä
   url: /contact

social:
   github: kasinobonuksia
   twitter: Veikkaajat
   email: 38805140+kasinobonuksia@users.noreply.github.com

google_analytics: 